"""Shared caller-evidence vocabularies."""
from enum import Enum

class CallerRunStatus(str, Enum):
    PLANNED="PLANNED"; RUNNING="RUNNING"; SUCCEEDED="SUCCEEDED"; FAILED="FAILED"
    DRY_RUN="DRY_RUN"; TOOL_MISSING="TOOL_MISSING"; INPUT_MISSING="INPUT_MISSING"
    UNSUPPORTED_VERSION="UNSUPPORTED_VERSION"; UNSUPPORTED_FORMAT="UNSUPPORTED_FORMAT"

RAW_READS = "RAW_READS"
ASSEMBLED_CONTIG = "ASSEMBLED_CONTIG"
UNASSIGNED = "UNASSIGNED"
DIRECT_SEQUENCE_ASSOCIATION = "DIRECT_SEQUENCE_ASSOCIATION"
